# Generated by Django 4.1.6 on 2023-02-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_chitchat_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitchat',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=255),
        ),
    ]
