# Generated by Django 4.1.6 on 2023-02-17 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
